### ISSUE TITLE
【功能模块开发】认证

### ISSUE THREAD

**Issue by A0nameless0man** [ThinkSpiritLab/heng-controller#11]

**Comment by Nugine** [comment]
认证模块需要管理外部系统和评测端的密钥对，提供生成、注销的接口，还需要实现 HTTP 签名校验。

相关文档：<https://github.com/ThinkSpiritLab/Heng-Protocol/tree/master/docs>

通信协议中尚未定义密钥接口的格式。

**Comment by WanchengWildMan** [comment]
SecretKey是客户系统保密的，既然签名校验要用到，那么就是说控制端也需要存吗？

**Comment by WanchengWildMan** [comment]
外部系统和评测端的密钥对和客户系统的AccessKey还有SecretKey之间的关系确实理解不明白了，
这个接口是生成和注销AccessKey和SecretKey的吧，那么角色是可以编码在AccessKey然后由guard提取出来去鉴权吗？

**Comment by Nugine** [comment]
控制端存储所有 AK 和 SK。
我们为每个外部系统(客户系统)各分配一对 AK 和 SK，保证只有已被授权的外部系统可以创建评测任务。
部署评测端时也需要 AK 和 SK，保证只有受信任的评测端可以连接到控制端。
控制端配置中要指定 root AK 和 root SK，作为所有 AK 和 SK 的权限来源。

每对密钥一定是三种类别之一：Root、外部系统、评测端。Root 同时具有外部系统和评测端的权限。

控制端的认证模块需要实现：

1. 增加配置，指定 root AK 和 root SK
2. 实现 HTTP 签名校验 (这个可以抄评测端代码)
3. 实现密钥对的存储、查找，作为 service（密钥对可以放进 redis）
4. 实现生成、注销密钥对的 HTTP 接口（只有 root 可以访问这两个接口）
5. 增加 guard，阻止签名不一致的请求
6. 增加 guard，阻止权限不一致的请求，例如外部系统不能访问评测端的 HTTP 接口

签名验证方法：<https://github.com/ThinkSpiritLab/Heng-Protocol/blob/master/docs/common.md>

@WanchengWildMan @A0nameless0man 看看对不对

**Comment by WanchengWildMan** [comment]
ak和sk要定过期时间吗？现在写的是根据ak来找sk，如果定的话，是不是就要把sk和生成的时间戳封装然后序列化一下存redis？

**Comment by Nugine** [comment]
> ak和sk要定过期时间吗？现在写的是根据ak来找sk，如果定的话，是不是就要把sk和生成的时间戳封装然后序列化一下存redis？

目前应该不需要自动过期，因为有手动注销的方法。

**Comment by WanchengWildMan** [comment]
那我现在写的就是redis里面对admin和user的key开两个hset，键是ak，值是sk，，

**Comment by Nugine** [comment]
> 那我现在写的就是redis里面对admin和user的key开两个hset，键是ak，值是sk，，

还要能判断密钥类别，外部系统不能访问给评测端用的接口，反之一样。

**Comment by A0nameless0man** [comment]
要不考虑使用jwt作为ak

**Comment by WanchengWildMan** [comment]
> > 那我现在写的就是 redis 里面对 admin 和 user 的 key 开两个 hset，键是 ak，值是 sk，，
> 
> 还要能判断密钥类别，外部系统不能访问给评测端用的接口，反之一样。

写的是去两个hset里面找，在哪个里面找到就是哪种类型

**Comment by WanchengWildMan** [comment]
> 要不考虑使用 jwt 作为 ak

emm目前找了一波还没见过这种方法？可以写一波）

**Comment by A0nameless0man** [comment]
> 那我现在写的就是redis里面对admin和user的key开两个hset，键是ak，值是sk，，

密钥类别有三类啊……建议存 HashMap<ak,Tuple<sk,type>>

**Comment by Nugine** [comment]
> 要不考虑使用jwt作为ak

jwt 不是这么用的。

AK和SK的生成只需要满足两个性质：唯一，不可预测。
强一点的话，所有可能的AK都只能生成注销一轮。弱一点的话，已注销的AK可以被再次生成，但必须匹配不同的SK。

**Comment by A0nameless0man** [comment]
那要不要考虑UUID？

**Comment by Nugine** [comment]
> 那要不要考虑UUID？

满足要求即可。

还有个软性要求：AK和SK的画风最好和常见的一致，不要太长（指几百字节）

**Comment by A0nameless0man** [comment]
那就ak是UUID1或2，SK是随机的64个字节经过Base64编码得到的结果？或者提高一下sk的可读性，使用十六进制编码。

**Comment by Nugine** [comment]
> 那就ak是UUID1或2，SK是随机的64个字节经过Base64编码得到的结果？或者提高一下sk的可读性，使用十六进制编码。

uuid v1 会向系统外暴露不必要的信息，v2 在大部分实现中都缺失，v3和v5 使用命名空间和名称生成，区别仅在于哈希算法，v4 是全随机。

所以v1和v2不可用……

**Comment by A0nameless0man** [comment]
V1可以保障不会重复吧，虽然V4重复的概率也极小罢了
