### ISSUE TITLE
【功能模块开发】外部系统模块

### ISSUE THREAD

**Issue by A0nameless0man** [ThinkSpiritLab/heng-controller#8]
这个模块负责管理与外部系统的连接，进行结果和状态更新的回调，维护任务的存储
@revue-starlight

**Comment by revue-starlight** [comment]
ExternalProtocol的文档里好像没有提及 interface JudgeRequest的内容。 有没有详细的文档

**Comment by Nugine** [comment]
> ExternalProtocol的文档里好像没有提及 interface JudgeRequest的内容。 有没有详细的文档

现在已经更新，类型定义在代码中 <https://github.com/ThinkSpiritLab/Heng-Protocol/blob/master/external-protocol/index.ts>
