### ISSUE TITLE
【功能模块开发】评测机交互模块

### ISSUE THREAD

**Issue by A0nameless0man** [ThinkSpiritLab/heng-controller#9]
这个模块负责与评测机交互，维护任务id与下发给评测机的运行id之间的映射，执行任务调度/评测机池的任务下发指令，向评测机池通知评测机的变化。当断线时，将未完成的评测放回队列。当有计划关闭时，向评测机下发指令。

**Comment by A0nameless0man** [comment]
>  12:02:10
> 只传给评测机池一个id吗
> 
>  12:02:17
> 不要性能信息吗
> 
>  12:07:51
> 还是说准备一律给评测机加满任务
> 
> NULL 12:08:13
> 性能信息在注册token的时候已经传过了吧

**Comment by A0nameless0man** [comment]
![PPSNN6D6UMLNU@C `N6FQNH](https://user-images.githubusercontent.com/17798917/98464624-23724300-21ff-11eb-842f-d6f339e9bd4c.jpg)

>  16:46:37
> 这个有什么规划吗，好像没有引用
> 
> NULL 16:48:15
> 而且打Log的时候有用
> 
> 16:48:31
> 我寻思着里面没几个状态能传上来啊）
> 
> NULL 16:51:52
> 这个确实
> 
> NULL 16:52:03
> 但是逻辑上是存在的
>

**Comment by A0nameless0man** [comment]
>  19:56:02
> 恢复时间接受指定吗
>
> NULL 19:56:10
> 指定 
> 
> NULL 19:56:04
> 控制端断开包括踢下线和系统重启
> 
> NULL 19:56:19
> 一般用于系统重启
> 
> NULL 19:56:35
> 免得手动重启所有评测机
> 
>  19:57:23
> 实际上控制端重启了
> 
>  19:57:28
> ws就断了
> 
> NULL 19:57:49
> 但是这样会带来错误信息（Log）
> 
> NULL 19:58:02
> 而重启是计划中行为
> 
> NULL 19:58:13
> 不应当带来Error类的log
>

**Comment by Handgrip** [comment]
pending：

- [ ] 评测端发送空的控制消息，评测端应当回复当前设置，以便查看或调整在线评测端的某些设置。
- [ ] 令牌桶移到内存内以减轻消息队列的压力+简化代码。
- [ ] CreateJudge消息只可能走进程内部，其他类型消息可能跨进程，改为pubsub或者维持现状。
- [ ] 若手动调用Exit，评测机超时未关闭，主动断开连接。

如有疏漏请补充。

**Comment by Flaryer** [comment]
pending：

1. 评测端发送空的控制消息，评测端应当回复当前设置，以便查看或调整在线评测端的某些设置。
2. 令牌桶移到内存内以减轻消息队列的压力+简化代码。
3. CreateJudge消息只可能走进程内部，其他类型消息可能跨进程，改为pubsub或者维持现状。
4. 若手动调用Exit，评测机超时未关闭，主动断开连接。

如有疏漏请补充。

**Comment by A0nameless0man** [comment]
关于Gateway的配置问题，我之前的尝试中，这样是可以的 https://github.com/ThinkSpiritLab/heng-controller/blob/cf4e14ac2cb9937a1db9c40b0fadfffa5c648413/src/judger/judger.gateway.ts#L13

**Comment by Handgrip** [comment]
> 关于Gateway的配置问题，我之前的尝试中，这样是可以的
> 
> https://github.com/ThinkSpiritLab/heng-controller/blob/cf4e14ac2cb9937a1db9c40b0fadfffa5c648413/src/judger/judger.gateway.ts#L13

我测试的时候，貌似连接的时候，任何path都能通过

**Comment by A0nameless0man** [comment]
> > 关于Gateway的配置问题，我之前的尝试中，这样是可以的
> > https://github.com/ThinkSpiritLab/heng-controller/blob/cf4e14ac2cb9937a1db9c40b0fadfffa5c648413/src/judger/judger.gateway.ts#L13
> 
> 我测试的时候，貌似连接的时候，任何path都能通过

我测试时，路径不对可以open但是消息被吞了

**Comment by Handgrip** [comment]
> > > 关于Gateway的配置问题，我之前的尝试中，这样是可以的
> > > https://github.com/ThinkSpiritLab/heng-controller/blob/cf4e14ac2cb9937a1db9c40b0fadfffa5c648413/src/judger/judger.gateway.ts#L13
> > 
> > 
> > 我测试的时候，貌似连接的时候，任何path都能通过
> 
> 我测试时，路径不对可以open但是消息被吞了

那看起来还是要手动判断path踢下线的

**Comment by A0nameless0man** [comment]
基本上是open和close事件同时触发

**Comment by A0nameless0man** [comment]
回学校后再试吧

**Comment by A0nameless0man** [comment]
在WS断联事件中，要调用judgerPoolService的logout方法
